name:                dict
version:             2019.4.24
github:              "magicloud/dict"
license:             BSD3
author:              "Magicloud"
maintainer:          "magiclouds@gmail.com"
copyright:           "None"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            desktop

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/magicloud/dict#readme>

dependencies:
- base >= 4.7 && < 5
- http-client-tls
- http-client
- xml-conduit
- html-conduit
- text

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  dict-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - dict
